name: Docker Image CI

on:
  push:
    branches: [ main ]

env:
  REPO: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: image env in lower case
        run: |
          echo "IMAGE_NAME=$(echo $REGISTRY/$REPO | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          RELEASE_IMAGE: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBE_NAMESPACE: budg
        with:
          args: set image deployment/budg-frontend frontend=${{ env.RELEASE_IMAGE }} --record -n $KUBE_NAMESPACE